% -------------------------------------------------------------------
%  Generated by MATLAB on 19-Feb-2021 18:34:18
%  MATLAB version: 9.1.0.441655 (R2016b)
% -------------------------------------------------------------------
saveVarsMat = load('matlab.mat');

B = 0.01;

J = 5;

Kephi = 1.6;

Kh = 0.5;

Kp = 0.5;

La = 0.1;

Ra = 0.5;

TL = 20;

b = 1;

m = 1;

tau_a = 0.2;

tau_m = 500;

tout = saveVarsMat.tout; % <1543x1 double> too many elements

clear saveVarsMat;
